apiVersion: v1
kind: Service
metadata:
  name: agno-agent-service
spec:
  selector:
    app: agno-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7777
  type: LoadBalancer  # or ClusterIP if used internally
